package com.example.tests;

import edreams.PageObject.EdreamsSearchPage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.Keymap;
import org.apache.commons.io.FileUtils;
import org.apache.james.mime4j.field.datetime.DateTime;
import org.junit.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import org.junit.rules.TestName;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Edreams {
  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();
  @Rule public TestName name = new TestName();


  @Before
  public void setUp() throws Exception {
    driver = new FirefoxDriver();
    baseUrl = "http://www.edreams.com/";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }
  @Test
  public void testEdreamsAutoGenerated() throws Exception {
    driver.get(baseUrl + "/");
    driver.findElement(By.xpath("//div[@id='flights-manager']/div[2]/div/ul/li")).click();
    driver.findElement(By.cssSelector("input.od-airportselector-input.airportselector_input")).clear();
    //problema en el sedKeys -> click del span[2]
    driver.findElement(By.cssSelector("input.od-airportselector-input.airportselector_input")).sendKeys("Mad");
    driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div/span[2]")).click();
    driver.findElement(By.cssSelector("div.od-aside-button.inc")).click();
    driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div[2]/div[2]/div/div[2]/div/div[3]")).click();
    driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div[2]/div[3]/div/div[2]/div/div[3]")).click();
    driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div[2]/div[3]/div/div[2]/div/div[2]")).click();
    driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div[2]/div[2]/div/div[2]/div/div[2]")).click();
    assertEquals("2 adults", driver.findElement(By.id("passengers_selector")).getText());
  }
  

  @Test
  public void testEdreamsModified() throws InterruptedException, Exception  {
    //added a try cach to get the errors!
    try
    {
        //about:permissions
        driver.manage().window().maximize();
        WebDriverWait wait = new WebDriverWait(driver, 10);
        driver.get(baseUrl);
        driver.findElement(By.xpath("//div[@id='flights-manager']/div[2]/div/ul/li")).click();
        driver.findElement(By.cssSelector("input.od-airportselector-input.airportselector_input")).clear();
        driver.findElement(By.cssSelector("input.od-airportselector-input.airportselector_input")).sendKeys("Mad");
        Thread.sleep(5000); //wait a bit to the modal! and then press return.
        driver.findElement(By.cssSelector("input.od-airportselector-input.airportselector_input")).sendKeys(Keys.RETURN);
        driver.findElement(By.cssSelector("input.od-airportselector-input.airportselector_input")).sendKeys(Keys.TAB);
        //wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("css=button.closeBtn.od-flightsManager-close-button")));
        //driver.findElement(By.cssSelector("css=button.closeBtn.od-flightsManager-close-button")).click();

        driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div/span[2]")).click();
        driver.findElement(By.cssSelector("div.od-aside-button.inc")).click();
        driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div[2]/div[2]/div/div[2]/div/div[3]")).click();
        driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div[2]/div[3]/div/div[2]/div/div[3]")).click();
        driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div[2]/div[3]/div/div[2]/div/div[2]")).click();
        driver.findElement(By.xpath("//div[@id='pax-selector']/div/div/div[2]/div[2]/div/div[2]/div/div[2]")).click();
        assertEquals(takeScreenShot("Assert"),"2 adults", driver.findElement(By.id("passengers_selector")).getText());
    } 
    catch (Exception ex)
    {
        
        System.err.println("Error in !" + ex.getMessage());
        throw ex;
    }
  }
  
  private String takeScreenShot(String fname){
    try {
            File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
            String imageFileDir = System.getProperty("selenium.screenshot.dir");
            if (imageFileDir == null)
                imageFileDir = System.getProperty("java.io.tmpdir");
            FileUtils.copyFile(scrFile, new File(imageFileDir, fname));
            return "Snapshot with error stored in " + imageFileDir;
        } catch (IOException ex) {
            Logger.getLogger(Edreams.class.getName()).log(Level.SEVERE, null, ex);
            return "Error storing snaphsot!"+ ex.getMessage();
        }
    }
  
  
   @Test
  public void testEdreamsPageObject() throws InterruptedException  {
    //added a try cach to get the errors!
    try
    {
        //about:permissions
        driver.manage().window().maximize();
        EdreamsSearchPage page = new EdreamsSearchPage(driver);
        page.open();
        page.search("mad","",2,3);
        
        assertEquals("2 adults", page.getPassangerSelectLiteral());
        assertEquals("2 adults", driver.findElement(By.id("passengers_selector")).getText(),
                takeScreenShot("Assert" + new Date() + name.getMethodName()));
        
          
    } 
    catch (Exception ex)
    {
        takeScreenShot(new Date() + "ERROR-Exception!In" + name.getMethodName());
        System.err.println("Error in !" + ex.getMessage());
        throw ex;
    }
  }
  
  @After
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }

  private boolean isAlertPresent() {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

  private String closeAlertAndGetItsText() {
    try {
      Alert alert = driver.switchTo().alert();
      String alertText = alert.getText();
      if (acceptNextAlert) {
        alert.accept();
      } else {
        alert.dismiss();
      }
      return alertText;
    } finally {
      acceptNextAlert = true;
    }
  }
  
  
}
